"use client";

import { useState } from "react";
import Link from "next/link";

export default function SignupPage() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/auth/signup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage(data.message); setName(""); setEmail(""); } catch (e) { setError(e.message || "Could not submit request."); } finally { setBusy(false); } };
  return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: "1rem", background: "#fff8d8" }}><form onSubmit={submit} className="glass-panel" style={{ width: "100%", maxWidth: 460, padding: "2rem", background: "#fff" }}><Link href="/login" style={{ fontSize: "0.8rem", color: "#0f172a", fontWeight: 800 }}>← Back to sign in</Link><h1 style={{ fontSize: "1.5rem", fontWeight: 900, margin: "1rem 0 0.5rem" }}>Request staff access</h1><p style={{ color: "#64748b", fontSize: "0.85rem", marginBottom: "1rem" }}>Your account stays disabled until an administrator reviews and assigns your role.</p>{error && <p role="alert" style={{ color: "#b91c1c", fontWeight: 700 }}>{error}</p>}{message && <p role="status" style={{ color: "#047857", fontWeight: 700 }}>{message}</p>}<label style={{ display: "grid", gap: 6, fontSize: "0.8rem", fontWeight: 800 }}>Full name<input required value={name} onChange={e => setName(e.target.value)} style={{ padding: "0.7rem", border: "1px solid #94a3b8", borderRadius: 8 }}/></label><label style={{ display: "grid", gap: 6, fontSize: "0.8rem", fontWeight: 800, marginTop: "0.8rem" }}>Work email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} style={{ padding: "0.7rem", border: "1px solid #94a3b8", borderRadius: 8 }}/></label><button disabled={busy} className="khandoli-btn-yellow" style={{ width: "100%", justifyContent: "center", marginTop: "1rem" }}>{busy ? "Submitting…" : "Request account"}</button></form></main>;
}
